version: '3'
services:
  slackbot.compose:
    build: .
    image: node-dev:1.0
    tty: true
    volumes:
      - $PWD/node:/app
    environment:
      - SLACK_CHANNEL
      - SLACK_BOT_TOKEN
      - SLACK_APP_TOKEN
    command: npm start
