version: '3'
services:
  slackbot.compose:
    build: .
    tty: true
    volumes:
      - $PWD/app:/app
    environment:
      - SLACK_CHANNEL
      - SLACK_BOT_TOKEN
      - SLACK_APP_TOKEN
    command: npm start
